### PR TITLE
Update usage of requests-cache and pin version

### PR DESCRIPTION
**Pull request by JWCook**
Hi there, a [new version of requests-cache](https://github.com/reclosedev/requests-cache/blob/master/HISTORY.md) was just released, so here are a few minor changes to update its usage.

* Pin version to to 0.6.* in `setup.py` and Pipfile (since future releases could potentially introduce breaking changes)
  * Update `Pipfile.lock`
* Pass backend type/path kwargs to `CachedSession` instead of directly creating a `DbDict` (the internal import path has changed)
* Use `CachedSession.remove_expired_responses()` to revalidate the cache instead of `CachedSession.cache.remove_old_entries()`
  * This also now accepts `timedelta`s in addition to `datetime`s
* Import existing `CACHE_CONFIG` in `patent_client.epo.inpadoc.session.py`

### CODE REVIEW

**Comment by JWCook** [comment]
Looks like I broke some tests.  I'll try to get those fixed.

**Comment by JWCook** [comment]
Hm, with some debug output, it looks like the tests on Travis CI are getting the same response I am locally, which is causing a `JSONDecodeError`.
```
b'<error><code>401</code><message>ClientId is Invalid</message>\n\t\t\t</error>\n\t\t'
``` 
Logs: https://travis-ci.org/github/parkerhancock/patent_client/builds/766551315

It looks like the creds are set as environment variables in Travis CI, and which doesn't have anything to do with requests-cache, so I'm not sure how I managed to break that.

**Comment by parkerhancock** [comment]
Thank you for this. I'm testing locally, and will see if I can sort out the Travis CI issue.

**Comment by JWCook** [comment]
Ah! I see what I did now. The `CACHE_CONFIG` in `patent_client/__init__.py` includes `allowable_methods=('GET', 'POST')`, and I updated `patent_client/epo/inpadoc/session.py` to use the same config. The authentication token request is a `POST`, so stale credentials could potentially be cached. Sorry about that!

I added an explicit `cache_disabled()` to that request to test that out, but I could also just revert all the changes to `patent_client/epo/inpadoc/session.py` if you'd prever.

**Comment by JWCook** [comment]
Well, the tests still failed, so there goes that theory! Including the `cache_disabled()` there is probably still a good idea, though.

**Comment by parkerhancock** [comment]
Build success! Thank you for submitting this, and apologies for how long it took to finally review and accept. Thanks again!

**Pull request merged**
